#ifndef  GPIO_ALLWINNER_H6_H
#define  GPIO_ALLWINNER_H6_H

#include  <linux/bitops.h>



#define  ALLWINNER_DMA_MAP_SIZE     (0x400u)
#define  ALLWINNER_DMA_CHANNEL_NUM       (16u)
#define  ALLWINNER_DMA_DESC_LINK_END       (0xfffff800u)


#define  ALLWINNER_DMA_CFG_DATA_WIDTH       GENMASK(10,  9)
#define  ALLWINNER_DMA_CFG_ADDR_MODE        BIT(8)
#define  ALLWINNER_DMA_CFG_DRQ_TYPE         GENMASK(5,  0)
#define  ALLWINNER_DMA_CFG_BLK_SIZE         GENMASK(7,  6)


enum {
    ALLWINNER_DMA_DRQ_SRAM =  0,
    ALLWINNER_DMA_DRQ_DRAM,
    ALLWINNER_DMA_DRQ_OWA,
    ALLWINNER_DMA_DRQ_I2S_PCM0,
    ALLWINNER_DMA_DRQ_I2S_PCM1,
    ALLWINNER_DMA_DRQ_I2S_PCM2,
    ALLWINNER_DMA_DRQ_I2S_PCM3,
    ALLWINNER_DMA_DRQ_DMIC,
    ALLWINNER_DMA_DRQ_CE,
    ALLWINNER_DMA_DRQ_NAND0,
    ALLWINNER_DMA_DRQ_UART0,
    ALLWINNER_DMA_DRQ_UART1,
    ALLWINNER_DMA_DRQ_UART2,
    ALLWINNER_DMA_DRQ_UART3,
    ALLWINNER_DMA_DRQ_SPI0,
    ALLWINNER_DMA_DRQ_SPI1,
    ALLWINNER_DMA_DRQ_OTG_EP1,
    ALLWINNER_DMA_DRQ_OTG_EP2,
    ALLWINNER_DMA_DRQ_OTG_EP3,
    ALLWINNER_DMA_DRQ_OTG_EP4,
    ALLWINNER_DMA_DRQ_AUDIO_HUB1,
    ALLWINNER_DMA_DRQ_AUDIO_HUB2,
    ALLWINNER_DMA_DRQ_AUDIO_HUB3,
    ALLWINNER_DMA_DRQ_MAX  =  ALLWINNER_DMA_DRQ_AUDIO_HUB3,
};





#endif
