#ifndef  GPIO_ALLWINNER_H6_H
#define  GPIO_ALLWINNER_H6_H

#include  <linux/bitops.h>


typedef enum  {
	ALLWINNER_H6_GPIO_DRV_LEVEL0 = 0,
	ALLWINNER_H6_GPIO_DRV_LEVEL1,
    ALLWINNER_H6_GPIO_DRV_LEVEL2,
    ALLWINNER_H6_GPIO_DRV_LEVEL3,
    ALLWINNER_H6_GPIO_DRV_MAX = ALLWINNER_H6_GPIO_DRV_LEVEL3,
} allwinner_h6_gpio_drv_mode_e;


typedef enum {
	ALLWINNER_H6_GPIO_PUPD_NO = 0,
	ALLWINNER_H6_GPIO_PUPD_UP,
	ALLWINNER_H6_GPIO_PUPD_DOWN,
    ALLWINNER_H6_GPIO_MAX = ALLWINNER_H6_GPIO_PUPD_DOWN
} allwinner_h6_gpio_pupd_e;


typedef enum {
	ALLWINNER_H6_PINMUX_AF0 = 0,
	ALLWINNER_H6_PINMUX_AF1,
	ALLWINNER_H6_PINMUX_AF2,
	ALLWINNER_H6_PINMUX_AF3,
	ALLWINNER_H6_PINMUX_AF4,
	ALLWINNER_H6_PINMUX_AF5,
	ALLWINNER_H6_PINMUX_AF6,
	ALLWINNER_H6_PINMUX_AF7,
	ALLWINNER_H6_PINMUX_MAX_AF  =  ALLWINNER_H6_PINMUX_AF7
} allwinner_h6_pinmux_af_e;


typedef enum {
	ALLWINNER_H6_PINMUX_POSITIVE_EDGE = 0,
	ALLWINNER_H6_PINMUX_NEGATIVE_EDGE,
	ALLWINNER_H6_PINMUX_HIGH_LEVEL,
	ALLWINNER_H6_PINMUX_LOW_LEVEL,
	ALLWINNER_H6_PINMUX_DOUBLE_EDGE,
	ALLWINNER_H6_PINMUX_MAX_TRIGGER  =  ALLWINNER_H6_PINMUX_DOUBLE_EDGE
} allwinner_h6_pinmux_trigger_type_e;



#define  ALLWINNER_H6_PINMUX_INPUT       ALLWINNER_H6_PINMUX_AF0
#define  ALLWINNER_H6_PINMUX_OUTPUT      ALLWINNER_H6_PINMUX_AF1
#define  ALLWINNER_H6_PINMUX_DISABLE     ALLWINNER_H6_PINMUX_AF7

#define  ALLWINNNER_H6_PIN_CFG_IDX(offset)      ((offset)>>3)
#define  ALLWINNNER_H6_PIN_CFG_SHIFT(offset)    (((offset) & 0x7) << 2)
#define  ALLWINNNER_H6_PIN_CFG_MASK              GENMASK(2, 0)

#define  ALLWINNNER_H6_PIN_PULL_IDX(offset)      ((offset)>>4)
#define  ALLWINNNER_H6_PIN_PULL_SHIFT(offset)    (((offset) & 0xf) << 1)
#define  ALLWINNNER_H6_PIN_PULL_MASK              GENMASK(1, 0)

#define  ALLWINNNER_H6_PIN_DRIVE_IDX(offset)      ((offset)>>4)
#define  ALLWINNNER_H6_PIN_DIRVE_SHIFT(offset)    (((offset) & 0xf) << 1)
#define  ALLWINNNER_H6_PIN_DRIVE_MASK             GENMASK(1, 0)

#define  ALLWINNNER_H6_PIN_TRIGGER_IDX(offset)      ((offset)>>3)
#define  ALLWINNNER_H6_PIN_TRIGGER_SHIFT(offset)    (((offset) & 0xf) << 2)
#define  ALLWINNNER_H6_PIN_TRIGGER_MASK             GENMASK(3, 0)


#endif
